//! Renders a role template as a Claude Code agent definition.
//!
//! Claude Code resolves a custom subagent from `<project>/.claude/agents/<name>.md`:
//! YAML frontmatter names the agent and its model, the body is its system
//! prompt. The body here is the very steering text taurhaus already renders
//! into a member's onboarding, so an agent definition and a mesh member read
//! the same role.

use std::collections::BTreeSet;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::coordination::delivery::{DeliveryRenderer, RoleContext};
use crate::session_scanner::cli_tool::spec;
use crate::templates::adapters::yaml_scalar;
use crate::templates::storage::{write_atomic_file, TemplateStoreError};
use crate::templates::types::RoleTemplate;

/// Marks a file as taurhaus-generated, on its own line right after the
/// frontmatter block. An agent definition without that header is user-authored
/// and is never overwritten — quoting the sentence elsewhere claims nothing.
pub const GENERATED_MARKER: &str = "# generated by taurhaus — edit the role template instead";

/// Render one role as the `.md` agent definition Claude Code reads.
pub fn render_agent_definition(role: &RoleTemplate) -> String {
    // A role may still carry the legacy `"gpt-5.4 high"` spelling in one field;
    // normalize it so the frontmatter separates model from effort the way a
    // launch does.
    let mut role = role.clone();
    role.normalize_model_fields();

    let mut rendered = String::from("---\n");
    rendered.push_str(&format!("name: {}\n", yaml_scalar(role.role_id.trim())));

    let description = trimmed(role.focus_area.as_deref()).unwrap_or_else(|| role.name.trim());
    if !description.is_empty() {
        rendered.push_str(&format!("description: {}\n", yaml_scalar(description)));
    }
    if let Some(model) = trimmed(Some(role.defaults.model.as_str())) {
        rendered.push_str(&format!("model: {}\n", yaml_scalar(model)));
    }
    if let Some(effort) = trimmed(role.defaults.reasoning_effort.as_deref()) {
        rendered.push_str(&format!("effort: {}\n", yaml_scalar(effort)));
    }
    rendered.push_str("---\n\n");
    rendered.push_str(GENERATED_MARKER);
    rendered.push('\n');

    let body = DeliveryRenderer::render_role_sections(&RoleContext::from(&role));
    if !body.is_empty() {
        rendered.push('\n');
        rendered.push_str(&body);
        rendered.push('\n');
    }

    rendered
}

/// What one export run wrote and what it deliberately left alone.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentDefinitionExport {
    /// Role ids whose definition file was written.
    pub written: Vec<String>,
    /// Role ids whose generated definition was deleted because the catalog no
    /// longer exports that role to Claude Code.
    pub removed: Vec<String>,
    pub skipped: Vec<SkippedAgentDefinition>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkippedAgentDefinition {
    pub role_id: String,
    pub reason: AgentDefinitionSkipReason,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentDefinitionSkipReason {
    /// A file already sits at that name and carries no generated marker, so a
    /// person wrote it.
    UserAuthored,
    /// The role id would not be a plain file name inside the agents directory.
    UnsafeRoleId,
    /// The role id is a safe file name but not an agent name Claude Code
    /// registers, so the file would never resolve as an `agentType`.
    UnsupportedAgentName,
}

/// Where Claude Code looks for a project's custom subagents.
pub fn agents_dir(project_dir: &Path) -> PathBuf {
    project_dir.join(".claude").join("agents")
}

/// The agents directory an export may actually write through, resolved against
/// the real project root.
///
/// `.claude` or `agents` can be a link — a dotfiles checkout, a Windows
/// junction — and an export that followed one out of the project would create
/// and delete files nobody selected. So each component is resolved and has to
/// land beneath the canonical root; a link that stays inside the project is
/// fine, one that leaves it (or dangles, which would have the missing tree
/// built out there) refuses the whole export.
fn resolved_agents_dir(project_dir: &Path) -> Result<PathBuf, TemplateStoreError> {
    let root = project_dir.canonicalize()?;
    let mut resolved = root.clone();

    for component in [".claude", "agents"] {
        let candidate = resolved.join(component);
        resolved = match std::fs::symlink_metadata(&candidate) {
            Ok(metadata) if is_link(&metadata) => {
                let real = candidate.canonicalize().map_err(|error| {
                    TemplateStoreError::Validation(format!(
                        "{} links nowhere this export can follow: {error}",
                        candidate.display()
                    ))
                })?;
                if !real.starts_with(&root) {
                    return Err(TemplateStoreError::Validation(format!(
                        "{} leaves the project: {}",
                        candidate.display(),
                        real.display()
                    )));
                }
                real
            }
            Ok(_) => candidate,
            // Nothing there yet: the export creates a plain directory under a
            // path every step of which we have already checked.
            Err(error) if error.kind() == ErrorKind::NotFound => candidate,
            Err(error) => return Err(TemplateStoreError::Io(error)),
        };
    }

    Ok(resolved)
}

/// Whether this is something an export must not follow or replace: a symlink
/// anywhere, and on Windows any reparse point — a junction, a mount point, an
/// app-exec link — since those redirect just as well.
fn is_link(metadata: &std::fs::Metadata) -> bool {
    if metadata.file_type().is_symlink() {
        return true;
    }
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;
        const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x400;
        return metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0;
    }
    #[cfg(not(windows))]
    false
}

/// Write one agent definition per role the harness registry says reads them,
/// and reconcile the directory with the catalog.
///
/// Only a generated file is ever replaced or deleted: a definition a person
/// wrote by hand is reported as skipped and left exactly as it is. A generated
/// file whose role left the catalog — renamed, deleted, or moved to a harness
/// that does not read agent definitions — is removed, because Claude Code and
/// a workflow's `agentType` would otherwise keep resolving instructions nobody
/// can edit any more. The project root has to exist already — an export never
/// brings a directory tree into being, so a mistyped or wrongly-resolved path
/// is refused instead of silently populated. Nothing outside the project is
/// ever written or deleted: see `resolved_agents_dir`.
pub fn export_agent_definitions(
    roles: &[RoleTemplate],
    project_dir: &Path,
) -> Result<AgentDefinitionExport, TemplateStoreError> {
    if !project_dir.is_dir() {
        return Err(TemplateStoreError::Validation(format!(
            "not a project directory: {}",
            project_dir.display()
        )));
    }

    let dir = resolved_agents_dir(project_dir)?;
    let mut export = AgentDefinitionExport::default();
    // Every name the catalog still claims, whether this run wrote it or left a
    // hand-written file at it. Anything else in the directory is either
    // someone's own agent or a leftover of ours.
    let mut claimed = BTreeSet::new();

    for role in roles
        .iter()
        .filter(|role| spec(role.defaults.cli_tool).capabilities.agent_definitions)
    {
        let file_name = match agent_file_name(&role.role_id) {
            Ok(file_name) => file_name,
            Err(reason) => {
                export.skip(role, reason);
                continue;
            }
        };

        let target = dir.join(&file_name);
        claimed.insert(file_name);
        match std::fs::symlink_metadata(&target) {
            // A link at an agent's own name is someone's: writing through it
            // would overwrite whatever it points at, replacing it would take
            // their link away.
            Ok(metadata) if is_link(&metadata) => {
                export.skip(role, AgentDefinitionSkipReason::UserAuthored);
                continue;
            }
            Ok(_) => {}
            Err(error) if error.kind() == ErrorKind::NotFound => {}
            Err(error) => return Err(TemplateStoreError::Io(error)),
        }
        match std::fs::read_to_string(&target) {
            Ok(existing) if !is_generated_definition(&existing) => {
                export.skip(role, AgentDefinitionSkipReason::UserAuthored);
                continue;
            }
            Ok(_) => {}
            // Ours is always UTF-8, so anything else at that name is someone's.
            Err(error)
                if matches!(
                    error.kind(),
                    ErrorKind::InvalidData | ErrorKind::IsADirectory
                ) =>
            {
                export.skip(role, AgentDefinitionSkipReason::UserAuthored);
                continue;
            }
            Err(error) if error.kind() == ErrorKind::NotFound => {}
            Err(error) => return Err(TemplateStoreError::Io(error)),
        }

        write_atomic_file(&target, render_agent_definition(role).as_bytes())?;
        export.written.push(role.role_id.clone());
    }

    export.removed = remove_obsolete_definitions(&dir, &claimed)?;

    Ok(export)
}

/// Delete the definitions this exporter generated for roles the catalog no
/// longer claims, and report their role ids. A file without the generated
/// marker is someone's own agent and is never touched, and neither is anything
/// that is not a `.md` file directly in the agents directory.
fn remove_obsolete_definitions(
    dir: &Path,
    claimed: &BTreeSet<String>,
) -> Result<Vec<String>, TemplateStoreError> {
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) if error.kind() == ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err(TemplateStoreError::Io(error)),
    };

    let mut removed = Vec::new();
    for entry in entries {
        let entry = entry?;
        let file_name = entry.file_name().to_string_lossy().into_owned();
        if claimed.contains(&file_name) {
            continue;
        }
        let Some(role_id) = file_name.strip_suffix(".md") else {
            continue;
        };
        // `DirEntry::metadata` does not follow a link, so a link is seen for
        // what it is and left where it is.
        let metadata = entry.metadata()?;
        if is_link(&metadata) || !metadata.is_file() {
            continue;
        }
        match std::fs::read_to_string(entry.path()) {
            Ok(existing) if is_generated_definition(&existing) => {}
            // Not ours: hand-written, or not even text we could have produced.
            Ok(_) => continue,
            Err(error) if error.kind() == ErrorKind::InvalidData => continue,
            // A concurrent delete already did the work.
            Err(error) if error.kind() == ErrorKind::NotFound => continue,
            Err(error) => return Err(TemplateStoreError::Io(error)),
        }

        std::fs::remove_file(entry.path())?;
        removed.push(role_id.to_string());
    }

    removed.sort();
    Ok(removed)
}

impl AgentDefinitionExport {
    fn skip(&mut self, role: &RoleTemplate, reason: AgentDefinitionSkipReason) {
        self.skipped.push(SkippedAgentDefinition {
            role_id: role.role_id.clone(),
            reason,
        });
    }
}

/// True when the file is one this exporter wrote: the marker stands on its own
/// line in the header position the renderer puts it in — directly after the
/// frontmatter block and the blank line that follows it. A file that merely
/// quotes the sentence somewhere in its body is someone's own agent, and a
/// person's agent is never overwritten or deleted.
fn is_generated_definition(contents: &str) -> bool {
    let mut lines = contents.lines();
    if lines.next() != Some("---") {
        return false;
    }
    loop {
        match lines.next() {
            Some("---") => break,
            // An unterminated frontmatter block is not our shape.
            None => return false,
            Some(_) => {}
        }
    }
    lines.next() == Some("") && lines.next() == Some(GENERATED_MARKER)
}

/// The file name for a role id, or the reason it cannot become one. A role id
/// has to be a plain name — the one guard that keeps an export inside the
/// agents directory — and it has to spell an agent name Claude Code will
/// register, because the id is what the frontmatter and a workflow's
/// `agentType` both name.
fn agent_file_name(role_id: &str) -> Result<String, AgentDefinitionSkipReason> {
    let is_plain_name = !role_id.is_empty()
        && role_id
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '-'));
    if !is_plain_name {
        return Err(AgentDefinitionSkipReason::UnsafeRoleId);
    }
    if !is_agent_name(role_id) {
        return Err(AgentDefinitionSkipReason::UnsupportedAgentName);
    }
    Ok(format!("{role_id}.md"))
}

/// Claude Code resolves a subagent by a lowercase, hyphen-separated name;
/// anything else lands on disk without ever being registered.
fn is_agent_name(role_id: &str) -> bool {
    role_id.split('-').all(|segment| {
        !segment.is_empty()
            && segment
                .chars()
                .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit())
    })
}

fn trimmed(value: Option<&str>) -> Option<&str> {
    value.map(str::trim).filter(|value| !value.is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::session_scanner::cli_tool::CliTool;
    use pretty_assertions::assert_eq;

    fn role(yaml: &str) -> RoleTemplate {
        serde_norway::from_str(yaml).expect("bundled role parses")
    }

    fn claude_role() -> RoleTemplate {
        role(include_str!(
            "../../resources/templates/roles/adversarial-reviewer-claude.yaml"
        ))
    }

    fn codex_role() -> RoleTemplate {
        role(include_str!(
            "../../resources/templates/roles/quick-dev-codex.yaml"
        ))
    }

    fn file_names(dir: &Path) -> Vec<String> {
        let mut names = std::fs::read_dir(dir)
            .expect("agents directory")
            .map(|entry| {
                entry
                    .expect("directory entry")
                    .file_name()
                    .to_string_lossy()
                    .into_owned()
            })
            .collect::<Vec<_>>();
        names.sort();
        names
    }

    #[test]
    fn renders_the_claude_golden() {
        let template = role(include_str!(
            "../../resources/templates/roles/adversarial-reviewer-claude.yaml"
        ));
        assert_eq!(
            render_agent_definition(&template),
            include_str!("../../tests/agent-definition-adversarial-reviewer-claude.golden.md")
        );
    }

    #[test]
    fn renders_the_codex_golden() {
        let template = role(include_str!(
            "../../resources/templates/roles/quick-dev-codex.yaml"
        ));
        assert_eq!(
            render_agent_definition(&template),
            include_str!("../../tests/agent-definition-quick-dev-codex.golden.md")
        );
    }

    #[test]
    fn judge_fable_exports_as_a_sane_claude_agent_definition() {
        let template = role(include_str!(
            "../../resources/templates/roles/judge-fable.yaml"
        ));
        let rendered = render_agent_definition(&template);

        assert!(rendered.starts_with(
            "---\nname: \"judge-fable\"\ndescription: \"Independent Claude-family judging of a shared evaluation cell under strict verdict isolation\"\nmodel: \"fable\"\neffort: \"high\"\n---\n"
        ));
        assert!(rendered.contains("Never see the other judge's verdict before recording your own."));
        assert!(rendered.contains("docs/team-delivery-standard.md"));
        assert!(rendered.contains("Behavioral Contract:"));
    }

    #[test]
    fn frontmatter_splits_a_legacy_model_spelling_and_quotes_unsafe_text() {
        let mut template = role(include_str!(
            "../../resources/templates/roles/quick-dev-codex.yaml"
        ));
        template.defaults.model = "gpt-5.4 high".to_string();
        template.defaults.reasoning_effort = None;
        template.focus_area = Some("Reviews: risk first, \"then\" scope".to_string());

        let rendered = render_agent_definition(&template);
        let frontmatter = rendered
            .split("---\n")
            .nth(1)
            .expect("rendered frontmatter block");

        assert_eq!(
            frontmatter,
            concat!(
                "name: \"quick-dev-codex\"\n",
                "description: \"Reviews: risk first, \\\"then\\\" scope\"\n",
                "model: \"gpt-5.4\"\n",
                "effort: \"high\"\n"
            )
        );
    }

    #[test]
    fn renders_the_agy_golden() {
        let template = role(include_str!(
            "../../resources/templates/roles/antigravity-orchestrator.yaml"
        ));
        assert_eq!(
            render_agent_definition(&template),
            include_str!("../../tests/agent-definition-antigravity-orchestrator.golden.md")
        );
    }

    #[test]
    fn the_frontmatter_parses_as_yaml_even_when_the_role_text_fights_it() {
        let mut template = claude_role();
        let hostile = "Reviews: \"risk\" first\nand # scope second\ttoo";
        template.focus_area = Some(hostile.to_string());

        let rendered = render_agent_definition(&template);
        let frontmatter = rendered
            .split("---\n")
            .nth(1)
            .expect("rendered frontmatter block");
        let parsed: serde_norway::Value =
            serde_norway::from_str(frontmatter).expect("frontmatter parses as YAML");

        assert_eq!(parsed["name"].as_str(), Some("adversarial-reviewer-claude"));
        assert_eq!(parsed["description"].as_str(), Some(hostile));
        assert_eq!(parsed["model"].as_str(), Some("opus"));
        assert_eq!(parsed["effort"].as_str(), Some("high"));
    }

    #[test]
    fn exports_one_file_per_claude_role_and_skips_the_other_harnesses() {
        let project = tempfile::tempdir().expect("project dir");
        let roles = vec![claude_role(), codex_role()];

        let result =
            export_agent_definitions(&roles, project.path()).expect("export writes definitions");

        assert_eq!(
            result.written,
            vec!["adversarial-reviewer-claude".to_string()]
        );
        assert!(result.skipped.is_empty());
        let dir = agents_dir(project.path());
        assert_eq!(
            file_names(&dir),
            vec!["adversarial-reviewer-claude.md".to_string()]
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("adversarial-reviewer-claude.md"))
                .expect("written definition"),
            include_str!("../../tests/agent-definition-adversarial-reviewer-claude.golden.md")
        );
    }

    #[test]
    fn a_generated_file_is_replaced_and_a_user_authored_agent_is_left_alone() {
        let project = tempfile::tempdir().expect("project dir");
        let dir = agents_dir(project.path());
        std::fs::create_dir_all(&dir).expect("agents directory");
        std::fs::write(
            dir.join("adversarial-reviewer-claude.md"),
            format!("---\nname: stale\n---\n\n{GENERATED_MARKER}\n"),
        )
        .expect("stale generated definition");

        let mut mine = claude_role();
        mine.role_id = "hand-written".to_string();
        std::fs::write(
            dir.join("hand-written.md"),
            "---\nname: mine\n---\n\nMy agent.\n",
        )
        .expect("user authored definition");

        let roles = vec![claude_role(), mine];
        let result = export_agent_definitions(&roles, project.path()).expect("export runs");

        assert_eq!(
            result.written,
            vec!["adversarial-reviewer-claude".to_string()]
        );
        assert_eq!(
            result.skipped,
            vec![SkippedAgentDefinition {
                role_id: "hand-written".to_string(),
                reason: AgentDefinitionSkipReason::UserAuthored,
            }]
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("adversarial-reviewer-claude.md"))
                .expect("regenerated"),
            include_str!("../../tests/agent-definition-adversarial-reviewer-claude.golden.md")
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("hand-written.md")).expect("untouched"),
            "---\nname: mine\n---\n\nMy agent.\n"
        );
    }

    #[test]
    fn a_role_id_that_is_not_a_plain_file_name_never_escapes_the_agents_directory() {
        let project = tempfile::tempdir().expect("project dir");
        let mut traversal = claude_role();
        traversal.role_id = "../../escaped".to_string();

        let result = export_agent_definitions(&[traversal], project.path()).expect("export runs");

        assert!(result.written.is_empty());
        assert_eq!(
            result.skipped,
            vec![SkippedAgentDefinition {
                role_id: "../../escaped".to_string(),
                reason: AgentDefinitionSkipReason::UnsafeRoleId,
            }]
        );
        assert!(!project.path().join("escaped.md").exists());
        assert!(!agents_dir(project.path()).exists());
    }

    #[test]
    fn a_project_root_that_is_not_a_directory_is_refused_instead_of_created() {
        // Regression: `just export-agents .` resolved the relative path under
        // `src-tauri`, and `write_atomic_file` created every missing parent, so
        // an export could silently land in a directory nobody asked for.
        let parent = tempfile::tempdir().expect("parent dir");
        let missing = parent.path().join("not-a-project");
        let file = parent.path().join("not-a-directory");
        std::fs::write(&file, "regular file").expect("regular file");

        for root in [&missing, &file] {
            let error = export_agent_definitions(&[claude_role()], root)
                .expect_err("a project root that is not a directory is refused");
            assert!(
                matches!(error, TemplateStoreError::Validation(_)),
                "unexpected error for {}: {error:?}",
                root.display()
            );
        }

        assert!(!missing.exists(), "the export created the project root");
        assert_eq!(
            std::fs::read_to_string(&file).expect("untouched file"),
            "regular file"
        );
    }

    #[test]
    fn a_role_id_claude_would_not_register_is_reported_instead_of_written() {
        // Claude Code resolves a subagent by a lowercase, hyphen-separated
        // name, so an id like `QA_reviewer` produces a file that is never
        // usable as a Workflow `agentType`.
        let project = tempfile::tempdir().expect("project dir");
        let mut shouty = claude_role();
        shouty.role_id = "QA_reviewer".to_string();

        let result = export_agent_definitions(&[shouty], project.path()).expect("export runs");

        assert!(result.written.is_empty());
        assert_eq!(
            result.skipped,
            vec![SkippedAgentDefinition {
                role_id: "QA_reviewer".to_string(),
                reason: AgentDefinitionSkipReason::UnsupportedAgentName,
            }]
        );
        assert!(!agents_dir(project.path()).join("QA_reviewer.md").exists());
    }

    #[test]
    fn every_bundled_role_id_still_spells_an_agent_name_claude_registers() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("resources")
            .join("templates")
            .join("roles");

        for entry in std::fs::read_dir(&dir).expect("bundled roles directory") {
            let path = entry.expect("directory entry").path();
            if path.extension().and_then(|ext| ext.to_str()) != Some("yaml") {
                continue;
            }
            let template = role(&std::fs::read_to_string(&path).expect("bundled role"));
            assert!(
                agent_file_name(&template.role_id).is_ok(),
                "{} is not an agent name Claude Code registers",
                template.role_id
            );
        }
    }

    #[test]
    fn a_re_export_deletes_the_generated_file_of_a_role_that_left_the_catalog() {
        // Regression: an export only wrote the roles it currently had, so the
        // definition of a role that was renamed or deleted stayed on disk and
        // Claude Code kept resolving an agent nobody could edit any more.
        let project = tempfile::tempdir().expect("project dir");
        let mut retired = claude_role();
        retired.role_id = "retired-reviewer".to_string();

        let first = export_agent_definitions(&[claude_role(), retired], project.path())
            .expect("first export");
        assert_eq!(
            first.written,
            vec![
                "adversarial-reviewer-claude".to_string(),
                "retired-reviewer".to_string()
            ]
        );
        assert!(first.removed.is_empty());

        let dir = agents_dir(project.path());
        std::fs::write(
            dir.join("hand-written.md"),
            "---\nname: mine\n---\n\nMy agent.\n",
        )
        .expect("user authored definition");

        let second = export_agent_definitions(&[claude_role()], project.path()).expect("re-export");

        assert_eq!(
            second.written,
            vec!["adversarial-reviewer-claude".to_string()]
        );
        assert_eq!(second.removed, vec!["retired-reviewer".to_string()]);
        assert_eq!(
            file_names(&dir),
            vec![
                "adversarial-reviewer-claude.md".to_string(),
                "hand-written.md".to_string()
            ]
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("hand-written.md")).expect("untouched"),
            "---\nname: mine\n---\n\nMy agent.\n"
        );
    }

    #[test]
    fn a_role_that_moved_to_another_harness_loses_its_generated_definition() {
        // Only Claude Code reads agent definitions, so a role that moved to a
        // different harness must stop being an agent as well.
        let project = tempfile::tempdir().expect("project dir");
        export_agent_definitions(&[claude_role()], project.path()).expect("first export");

        let mut moved = claude_role();
        moved.defaults.cli_tool = CliTool::Codex;
        let result = export_agent_definitions(&[moved], project.path()).expect("re-export");

        assert!(result.written.is_empty());
        assert_eq!(
            result.removed,
            vec!["adversarial-reviewer-claude".to_string()]
        );
        assert!(!agents_dir(project.path())
            .join("adversarial-reviewer-claude.md")
            .exists());
    }

    #[test]
    fn an_export_that_writes_nothing_still_leaves_a_foreign_agents_directory_alone() {
        // Nothing in `.claude/agents` is ours unless it carries the marker: an
        // export with no Claude roles at all removes nothing.
        let project = tempfile::tempdir().expect("project dir");
        let dir = agents_dir(project.path());
        std::fs::create_dir_all(dir.join("shared")).expect("agents directory");
        std::fs::write(dir.join("mine.md"), "---\nname: mine\n---\n").expect("hand written");
        std::fs::write(dir.join("notes.txt"), "not an agent").expect("stray file");

        let result = export_agent_definitions(&[codex_role()], project.path()).expect("export");

        assert!(result.written.is_empty());
        assert!(result.removed.is_empty());
        assert_eq!(
            file_names(&dir),
            vec![
                "mine.md".to_string(),
                "notes.txt".to_string(),
                "shared".to_string()
            ]
        );
    }

    #[test]
    fn export_leaves_no_temporary_file_behind() {
        let project = tempfile::tempdir().expect("project dir");
        let roles = vec![claude_role()];

        export_agent_definitions(&roles, project.path()).expect("first export");
        export_agent_definitions(&roles, project.path()).expect("second export");

        assert_eq!(
            file_names(&agents_dir(project.path())),
            vec!["adversarial-reviewer-claude.md".to_string()]
        );
    }

    #[test]
    fn an_agent_that_merely_quotes_the_marker_is_still_user_authored() {
        // Regression: ownership was inferred from the marker appearing
        // anywhere in the file, so a hand-written agent that quoted the
        // sentence — a house style note, a review checklist — was overwritten
        // by the next export.
        let project = tempfile::tempdir().expect("project dir");
        let dir = agents_dir(project.path());
        std::fs::create_dir_all(&dir).expect("agents directory");
        let quoting = format!(
            "---\nname: adversarial-reviewer-claude\n---\n\nMine. Ours start with `{GENERATED_MARKER}`.\n"
        );
        std::fs::write(dir.join("adversarial-reviewer-claude.md"), &quoting)
            .expect("user authored definition");

        let result = export_agent_definitions(&[claude_role()], project.path()).expect("export");

        assert!(result.written.is_empty());
        assert_eq!(
            result.skipped,
            vec![SkippedAgentDefinition {
                role_id: "adversarial-reviewer-claude".to_string(),
                reason: AgentDefinitionSkipReason::UserAuthored,
            }]
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("adversarial-reviewer-claude.md")).expect("untouched"),
            quoting
        );
    }

    #[test]
    fn pruning_leaves_an_agent_that_merely_quotes_the_marker_alone() {
        // The same mistaken ownership on the removal side deleted a file
        // nobody generated.
        let project = tempfile::tempdir().expect("project dir");
        let dir = agents_dir(project.path());
        std::fs::create_dir_all(&dir).expect("agents directory");
        let quoting =
            format!("---\nname: mine\n---\n\nNever write `{GENERATED_MARKER}` yourself.\n");
        std::fs::write(dir.join("mine.md"), &quoting).expect("user authored definition");

        let result = export_agent_definitions(&[claude_role()], project.path()).expect("export");

        assert!(result.removed.is_empty());
        assert_eq!(
            std::fs::read_to_string(dir.join("mine.md")).expect("untouched"),
            quoting
        );
    }

    #[test]
    fn only_the_marker_in_the_generated_header_position_claims_a_file() {
        let generated = render_agent_definition(&claude_role());
        assert!(is_generated_definition(&generated));
        // The same bytes an editor may have rewritten to CRLF are still ours.
        assert!(is_generated_definition(&generated.replace('\n', "\r\n")));

        for foreign in [
            format!("{GENERATED_MARKER}\n"),
            format!("---\nname: mine\n---\n\nMine.\n\n{GENERATED_MARKER}\n"),
            format!("---\nname: mine\n---\n\nMine, see `{GENERATED_MARKER}`.\n"),
            format!("Prelude\n---\nname: mine\n---\n\n{GENERATED_MARKER}\n"),
            "---\nname: mine\n".to_string(),
        ] {
            assert!(
                !is_generated_definition(&foreign),
                "claimed a file we did not write: {foreign:?}"
            );
        }
    }

    /// Link `link` to the directory `target`: a symlink on Unix, a directory
    /// symlink (a reparse point, like a junction) on Windows. Windows only
    /// allows one under developer mode or elevation, so a test that cannot
    /// create one has nothing to assert and returns.
    #[cfg(unix)]
    fn link_dir(target: &Path, link: &Path) -> std::io::Result<()> {
        std::os::unix::fs::symlink(target, link)
    }

    #[cfg(windows)]
    fn link_dir(target: &Path, link: &Path) -> std::io::Result<()> {
        std::os::windows::fs::symlink_dir(target, link)
    }

    #[cfg(unix)]
    fn link_file(target: &Path, link: &Path) -> std::io::Result<()> {
        std::os::unix::fs::symlink(target, link)
    }

    #[cfg(windows)]
    fn link_file(target: &Path, link: &Path) -> std::io::Result<()> {
        std::os::windows::fs::symlink_file(target, link)
    }

    fn generated(name: &str) -> String {
        format!("---\nname: {name}\n---\n\n{GENERATED_MARKER}\n")
    }

    #[test]
    fn an_agents_path_that_links_out_of_the_project_is_refused() {
        // Regression: `.claude/agents` was joined onto the project root and
        // written and pruned through blindly, so a linked component — a
        // dotfiles checkout, a Windows junction — let an export create and
        // delete files anywhere on disk.
        for linked in [".claude", "agents"] {
            let project = tempfile::tempdir().expect("project dir");
            let outside = tempfile::tempdir().expect("directory outside the project");
            let elsewhere = outside.path().join("agents");
            std::fs::create_dir_all(&elsewhere).expect("foreign agents directory");
            let victim = elsewhere.join("retired-reviewer.md");
            std::fs::write(&victim, generated("retired-reviewer")).expect("foreign generated file");

            let link = match linked {
                ".claude" => project.path().join(".claude"),
                _ => {
                    let claude = project.path().join(".claude");
                    std::fs::create_dir_all(&claude).expect("claude directory");
                    claude.join("agents")
                }
            };
            let target = if linked == ".claude" {
                outside.path().to_path_buf()
            } else {
                elsewhere.clone()
            };
            if link_dir(&target, &link).is_err() {
                return;
            }

            let error = export_agent_definitions(&[claude_role()], project.path())
                .expect_err("an agents path outside the project is refused");
            assert!(
                matches!(error, TemplateStoreError::Validation(_)),
                "unexpected error for a linked {linked}: {error:?}"
            );
            assert!(
                !elsewhere.join("adversarial-reviewer-claude.md").exists(),
                "the export wrote outside the project through {linked}"
            );
            assert!(
                victim.exists(),
                "the export deleted a file outside the project through {linked}"
            );
        }
    }

    #[test]
    fn a_dangling_agents_link_is_refused_instead_of_followed() {
        // A link to a directory that does not exist yet is the same escape:
        // creating the missing parents would build the foreign tree.
        let project = tempfile::tempdir().expect("project dir");
        let outside = tempfile::tempdir().expect("directory outside the project");
        let never_created = outside.path().join("agents");
        if link_dir(&never_created, &project.path().join(".claude")).is_err() {
            return;
        }

        let error = export_agent_definitions(&[claude_role()], project.path())
            .expect_err("a dangling agents link is refused");
        assert!(
            matches!(error, TemplateStoreError::Validation(_)),
            "unexpected error: {error:?}"
        );
        assert!(!never_created.exists(), "the export built a foreign tree");
    }

    #[test]
    fn an_agents_path_that_links_within_the_project_still_exports() {
        // A link is only a problem when it leaves the project; a project that
        // keeps its agents in a shared directory of its own still exports.
        let project = tempfile::tempdir().expect("project dir");
        let shared = project.path().join("shared-agents");
        std::fs::create_dir_all(&shared).expect("shared agents directory");
        std::fs::create_dir_all(project.path().join(".claude")).expect("claude directory");
        if link_dir(&shared, &project.path().join(".claude").join("agents")).is_err() {
            return;
        }

        let result = export_agent_definitions(&[claude_role()], project.path()).expect("export");

        assert_eq!(
            result.written,
            vec!["adversarial-reviewer-claude".to_string()]
        );
        assert_eq!(
            std::fs::read_to_string(shared.join("adversarial-reviewer-claude.md"))
                .expect("written definition"),
            include_str!("../../tests/agent-definition-adversarial-reviewer-claude.golden.md")
        );
    }

    #[test]
    fn a_linked_definition_is_left_alone_instead_of_written_through() {
        // A link at an agent's own name is someone's: following it would write
        // over whatever it points at, and replacing it would take their link.
        let project = tempfile::tempdir().expect("project dir");
        let dir = agents_dir(project.path());
        std::fs::create_dir_all(&dir).expect("agents directory");
        let outside = tempfile::tempdir().expect("directory outside the project");
        let pointee = outside.path().join("reviewer.md");
        std::fs::write(&pointee, generated("elsewhere")).expect("foreign generated file");
        if link_file(&pointee, &dir.join("adversarial-reviewer-claude.md")).is_err() {
            return;
        }
        let stray = outside.path().join("stray.md");
        std::fs::write(&stray, generated("stray")).expect("foreign generated file");
        if link_file(&stray, &dir.join("stray.md")).is_err() {
            return;
        }

        let result = export_agent_definitions(&[claude_role()], project.path()).expect("export");

        assert!(result.written.is_empty());
        assert_eq!(
            result.skipped,
            vec![SkippedAgentDefinition {
                role_id: "adversarial-reviewer-claude".to_string(),
                reason: AgentDefinitionSkipReason::UserAuthored,
            }]
        );
        assert!(result.removed.is_empty(), "a linked file was pruned");
        assert_eq!(
            std::fs::read_to_string(&pointee).expect("untouched"),
            generated("elsewhere")
        );
        assert!(stray.exists(), "pruning followed a link out of the project");
        assert!(dir
            .join("adversarial-reviewer-claude.md")
            .symlink_metadata()
            .expect("the link survives")
            .file_type()
            .is_symlink());
    }
}
