//! Renders a role template as a Claude Code agent definition.
//!
//! Claude Code resolves a custom subagent from `<project>/.claude/agents/<name>.md`:
//! YAML frontmatter names the agent and its model, the body is its system
//! prompt. The body here is the very steering text taurhaus already renders
//! into a member's onboarding, so an agent definition and a mesh member read
//! the same role.

use crate::coordination::delivery::{DeliveryRenderer, RoleContext};
use crate::templates::adapters::yaml_scalar;
use crate::templates::types::RoleTemplate;

/// Marks a file as taurhaus-generated. An agent definition without this line is
/// user-authored and is never overwritten.
pub const GENERATED_MARKER: &str = "# generated by taurhaus — edit the role template instead";

/// Render one role as the `.md` agent definition Claude Code reads.
pub fn render_agent_definition(role: &RoleTemplate) -> String {
    // A role may still carry the legacy `"gpt-5.4 high"` spelling in one field;
    // normalize it so the frontmatter separates model from effort the way a
    // launch does.
    let mut role = role.clone();
    role.normalize_model_fields();

    let mut rendered = String::from("---\n");
    rendered.push_str(&format!("name: {}\n", yaml_scalar(role.role_id.trim())));

    let description = trimmed(role.focus_area.as_deref()).unwrap_or_else(|| role.name.trim());
    if !description.is_empty() {
        rendered.push_str(&format!("description: {}\n", yaml_scalar(description)));
    }
    if let Some(model) = trimmed(Some(role.defaults.model.as_str())) {
        rendered.push_str(&format!("model: {}\n", yaml_scalar(model)));
    }
    if let Some(effort) = trimmed(role.defaults.reasoning_effort.as_deref()) {
        rendered.push_str(&format!("effort: {}\n", yaml_scalar(effort)));
    }
    rendered.push_str("---\n\n");
    rendered.push_str(GENERATED_MARKER);
    rendered.push('\n');

    let body = DeliveryRenderer::render_role_sections(&RoleContext::from(&role));
    if !body.is_empty() {
        rendered.push('\n');
        rendered.push_str(&body);
        rendered.push('\n');
    }

    rendered
}

fn trimmed(value: Option<&str>) -> Option<&str> {
    value.map(str::trim).filter(|value| !value.is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;

    fn role(yaml: &str) -> RoleTemplate {
        serde_norway::from_str(yaml).expect("bundled role parses")
    }

    #[test]
    fn renders_the_claude_golden() {
        let template = role(include_str!(
            "../../resources/templates/roles/claude-reviewer.yaml"
        ));
        assert_eq!(
            render_agent_definition(&template),
            include_str!("../../tests/agent-definition-claude-reviewer.golden.md")
        );
    }

    #[test]
    fn renders_the_codex_golden() {
        let template = role(include_str!(
            "../../resources/templates/roles/quick-dev-codex.yaml"
        ));
        assert_eq!(
            render_agent_definition(&template),
            include_str!("../../tests/agent-definition-quick-dev-codex.golden.md")
        );
    }

    #[test]
    fn frontmatter_splits_a_legacy_model_spelling_and_quotes_unsafe_text() {
        let mut template = role(include_str!(
            "../../resources/templates/roles/quick-dev-codex.yaml"
        ));
        template.defaults.model = "gpt-5.4 high".to_string();
        template.defaults.reasoning_effort = None;
        template.focus_area = Some("Reviews: risk first, \"then\" scope".to_string());

        let rendered = render_agent_definition(&template);
        let frontmatter = rendered
            .split("---\n")
            .nth(1)
            .expect("rendered frontmatter block");

        assert_eq!(
            frontmatter,
            concat!(
                "name: \"quick-dev-codex\"\n",
                "description: \"Reviews: risk first, \\\"then\\\" scope\"\n",
                "model: \"gpt-5.4\"\n",
                "effort: \"high\"\n"
            )
        );
    }

    #[test]
    fn renders_the_agy_golden() {
        let template = role(include_str!(
            "../../resources/templates/roles/antigravity-orchestrator.yaml"
        ));
        assert_eq!(
            render_agent_definition(&template),
            include_str!("../../tests/agent-definition-antigravity-orchestrator.golden.md")
        );
    }
}
