#!/usr/bin/env bash
# Bootstrap docs/images/infographics.manifest.yaml from taursult MCP generation DB.
#
# Queries taursult for all generations tagged "taurhaus-infographic", maps them
# to docs/images/ filenames, and emits a YAML manifest with full prompts and
# generation metadata. Images not found in taursult get stub entries.
#
# Usage:
#   ./scripts/bootstrap-infographic-manifest.sh
#
# Requires: python3, taursult MCP running (for initial data export)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFEST="$PROJECT_ROOT/docs/images/infographics.manifest.yaml"
IMAGES_DIR="$PROJECT_ROOT/docs/images"

python3 - "$IMAGES_DIR" "$MANIFEST" << 'PYTHON_SCRIPT'
import sys, os, json, subprocess, hashlib, glob
from datetime import datetime

images_dir = sys.argv[1]
manifest_path = sys.argv[2]

# Discover all jpg files in docs/images/
all_images = sorted(
    os.path.basename(f)
    for f in glob.glob(os.path.join(images_dir, "*.jpg"))
)

# Load taursult generation data via CLI query to the MCP's SQLite DB
taursult_db = os.path.expanduser("~/projects/taursult/queue/image_registry.db")
generations = {}

if os.path.exists(taursult_db):
    import sqlite3
    conn = sqlite3.connect(taursult_db)
    conn.row_factory = sqlite3.Row

    # Get all taurhaus-infographic tagged generations
    rows = conn.execute("""
        SELECT g.*, a.output_path, a.sha256 as artifact_sha256
        FROM image_generations g
        LEFT JOIN image_artifacts a ON g.generation_id = a.generation_id
        WHERE g.tag = 'taurhaus-infographic'
        ORDER BY g.created_at DESC
    """).fetchall()

    for row in rows:
        gen_id = row["generation_id"]
        if gen_id not in generations:
            generations[gen_id] = dict(row)
    conn.close()
else:
    print(f"Warning: taursult DB not found at {taursult_db}", file=sys.stderr)
    print("Generating stub-only manifest.", file=sys.stderr)

# Build mapping: output filename -> generation record
# Match by checking if the original output was copied to docs/images/
filename_to_gen = {}
gen_id_order = []  # track insertion order for the 8 regenerated images

for gen_id, gen in generations.items():
    output_path = gen.get("output_path", "")
    if not output_path:
        continue
    # We need to figure out which docs/images/ file this generation produced.
    # The workflow was: generate -> copy to docs/images/<name>.jpg -> optimize
    # We can match by generation order within the workflow.
    gen_id_order.append((gen_id, gen))

# The 8 generations in infographic-regen-v043 workflow map to these files
# (in generation order, oldest first):
regen_mapping = {
    "gen_e44f6310111c": "mesh-view-lifecycle.jpg",
    "gen_db88afd20f33": "coordination-architecture.jpg",
    "gen_76de2f01e73e": "system-architecture.jpg",
    "gen_b83de5b83ac9": "data-model.jpg",
    "gen_0d677aa29570": "task-aggregation.jpg",
    "gen_42e8a122830a": "file-rendering-pipeline.jpg",
    "gen_6ddd99f9cd2c": "build-release-pipeline.jpg",
    "gen_482a7ff491ee": "mesh-resume-liveness-sequence.jpg",
}

for gen_id, filename in regen_mapping.items():
    if gen_id in generations:
        filename_to_gen[filename] = generations[gen_id]

def image_id_from_filename(filename):
    """mesh-view-lifecycle.jpg -> mesh-view-lifecycle"""
    return filename.rsplit(".", 1)[0]

def escape_yaml_string(s):
    """Minimal escaping for YAML scalar strings."""
    if not s:
        return '""'
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

def indent(text, spaces):
    """Indent each line of text."""
    prefix = " " * spaces
    return "\n".join(prefix + line if line.strip() else "" for line in text.split("\n"))

# Write manifest
with open(manifest_path, "w") as f:
    f.write("# Infographic generation manifest for taurhaus documentation.\n")
    f.write("# Auto-generated by scripts/bootstrap-infographic-manifest.sh\n")
    f.write("# Full prompts stored here for self-sufficient regeneration.\n")
    f.write("#\n")
    f.write("# Workflow to update an image:\n")
    f.write("#   1. Find the entry below by image id\n")
    f.write("#   2. Copy the prompt, make edits for new content\n")
    f.write("#   3. Regenerate via taursult MCP (pass reference_image_paths for style)\n")
    f.write("#   4. Optimize: ./scripts/optimize-doc-image.sh <output> docs/images/<name>.jpg\n")
    f.write("#   5. Run: just update-infographic-manifest\n")
    f.write("\n")
    f.write("schema_version: 1\n\n")
    f.write("images:\n")

    for filename in all_images:
        img_id = image_id_from_filename(filename)
        gen = filename_to_gen.get(filename)

        f.write(f"\n  {img_id}:\n")
        f.write(f"    output_path: docs/images/{filename}\n")

        if gen:
            gen_id = gen.get("generation_id", "")
            model = gen.get("model", "")
            aspect = gen.get("aspect_ratio", "16:9")
            size = gen.get("image_size", "2K")
            sha256 = gen.get("artifact_sha256", "")
            created = gen.get("created_at", "")[:10]
            prompt = gen.get("prompt", "")
            ref_paths = gen.get("reference_image_paths", "")

            f.write(f"    status: active\n")
            f.write(f"    generation_id: {gen_id}\n")
            f.write(f"    recipe:\n")
            f.write(f"      model: {model}\n")
            f.write(f"      aspect_ratio: \"{aspect}\"\n")
            f.write(f"      image_size: {size}\n")

            # Reference image paths
            if ref_paths:
                try:
                    paths = json.loads(ref_paths) if isinstance(ref_paths, str) else ref_paths
                    if paths:
                        f.write(f"      reference_image_paths:\n")
                        for rp in paths:
                            # Convert absolute path to repo-relative
                            if "/projects/taurhaus/" in rp:
                                rp = rp.split("/projects/taurhaus/", 1)[1]
                            f.write(f"        - {rp}\n")
                except (json.JSONDecodeError, TypeError):
                    pass

            # Prompt as YAML block scalar
            f.write(f"      prompt: |\n")
            for line in prompt.split("\n"):
                if line.strip():
                    f.write(f"        {line}\n")
                else:
                    f.write(f"\n")

            f.write(f"    sha256: {sha256}\n")
            f.write(f"    updated_at: \"{created}\"\n")
            f.write(f"    history:\n")
            f.write(f"      - {gen_id}  # v0.4.4 infographic regeneration\n")

        else:
            # Stub entry for images without taursult generation data
            f.write(f"    status: active\n")
            f.write(f"    generation_id: null  # predates taursult MCP\n")
            f.write(f"    recipe:\n")
            f.write(f"      model: unknown\n")
            f.write(f"      aspect_ratio: \"16:9\"\n")
            f.write(f"      image_size: 2K\n")
            f.write(f"      prompt: |  # TODO: reconstruct prompt for this image\n")
            f.write(f"        (prompt not available — image predates taursult MCP)\n")
            f.write(f"    sha256: null\n")
            f.write(f"    updated_at: null\n")
            f.write(f"    history: []\n")

print(f"Wrote {manifest_path}")
print(f"  {len(filename_to_gen)} images with full generation data")
print(f"  {len(all_images) - len(filename_to_gen)} stub entries (pre-taursult)")
PYTHON_SCRIPT
