"""Offline evidence audit and read-only process census; no harness/auth access."""
import hashlib
import json
from pathlib import Path
import re
import subprocess

def privacy_scan(base):
    violations=[]; exemptions=[]; scanned=0
    auth_expression="Path('/home')/'mstie'/'.codex-account-b'/'auth.json'"
    auth_path='/'.join(['','home','mstie','.codex-account-b','auth.json'])
    operator_pattern=r'(?<![\w/-])' + '/' + r'home/[^/\s]+/(?!projects/(?:taurhaus-l4-resume-team|mesh-l4)(?:/|\b))[^\s"\']*'
    for path in base.rglob('*'):
        if not path.is_file() or '__pycache__' in path.parts: continue
        text=path.read_text(); scanned+=1
        if path.name=='controller.py':
            for allowed in [auth_expression,auth_path]:
                if allowed in text:
                    text=text.replace(allowed,'<authorized-auth-source>')
                    exemptions.append({'file':str(path.relative_to(base)),
                                       'rule':'Exact operator-authorized auth source expression; source code only'})
        if re.search(operator_pattern,text): violations.append(str(path.relative_to(base))+': operator path')
        if re.search(r'\bsk-[A-Za-z0-9_-]{20,}|\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+',text): violations.append(str(path.relative_to(base))+': credential pattern')
        if path.name.startswith('final-pane') and path.suffix=='.json':
            value=json.loads(text)
            if isinstance(value,dict) and len(value.get('lines',[]))>60: violations.append(path.name+': pane too long')
    return {'privacy_violations':violations,'privacy_files_scanned':scanned,
            'privacy_scope':'All text sidecars including Python sources; generated bytecode excluded',
            'privacy_exemptions':exemptions}


def main(BASE):
    records=[json.loads(l) for l in (BASE/'events.jsonl').read_text().splitlines()]
    isolation=next(r for r in records if r['kind']=='isolation')
    root=Path(isolation['environment']['CODEX_HOME']).parent
    marker=b'TAURHAUS_TRIAL_ID='+root.name.encode()+b'\0'
    owned=json.loads((BASE/'owned-before-cleanup.json').read_text())
    survivors=[]
    for proc in Path('/proc').iterdir():
        if not proc.name.isdigit(): continue
        try:
            ticks=(proc/'stat').read_text().rsplit(')',1)[1].split()[19]
            if marker in (proc/'environ').read_bytes() or any(int(proc.name)==p['pid'] and ticks==p['start_ticks'] for p in owned):
                survivors.append({'pid':int(proc.name),'start_ticks':ticks})
        except (FileNotFoundError,PermissionError,ProcessLookupError): pass
    privacy=privacy_scan(BASE)
    violations=privacy['privacy_violations']
    logs=[json.loads(l) for l in (BASE/'taurhaus.log.jsonl').read_text().splitlines()]
    assert all(not r.get('event','').startswith('usage.') for r in logs)
    assert sum(r.get('kind')=='rpc_request' and r['request']['method']=='coordination.resume_team' for r in records)<=1
    assert not survivors and not root.exists() and not violations
    mesh=Path('/home/mstie/projects/mesh-l4')
    result={'owned_processes_rechecked':len(owned),'survivors':survivors,'scratch_root_removed':not root.exists(),
            'auth_removed':not (root/'codex/auth.json').exists(),'shipped_mesh_binary_retained':(mesh/'target/debug/mesh').exists(),
            'mesh_descriptor_diff_exit':subprocess.run(['git','-C',str(mesh),'diff','--exit-code','--','src/delivery/app_server/capabilities.rs'],capture_output=True).returncode,
            'daemon_jsonl_rows':len(logs),**privacy,'runtime_seconds':round(records[-1]['at']-records[0]['at'],3),
            'executed_controller_and_support_commit':json.loads((BASE/'provenance.json').read_text())['controller_commit'],'gate_processes_excluded':'No gate is a trial seat; gate runner waits its own children.'}
    (BASE/'final-audit.json').write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps(result))


if __name__=='__main__':
    import sys
    main(Path(sys.argv[1]) if len(sys.argv)>1 else Path(__file__).resolve().parent)
