/**
 * A scratch `CODEX_HOME` for the live Codex compaction lane.
 *
 * The lane drives a real Codex subscription, so it needs the real credentials —
 * and nothing else. Only `auth.json` is copied: sessions, history and the local
 * databases stay in the operator's own home, and nothing is ever written back to
 * it. The managed `hooks.json`, the rollout transcripts and every mutation the
 * run causes land in the scratch copy.
 *
 * The operator's `config.toml` is deliberately *not* copied. It can register
 * things Codex executes — `notify`, MCP servers — and one of those, `notify`,
 * silently breaks the lane: taurhaus preserves a user-configured notifier
 * instead of installing its own (`commands/terminal_settings.rs`), and the
 * notifier taurhaus installs is the lane's only turn signal. The scratch home
 * therefore starts from a generated minimal config that the lane then adds its
 * own project trust and auto-compaction threshold to.
 */

import { appendFileSync, chmodSync, copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/** The only file copied out of the operator's real Codex home. */
export const CODEX_SCRATCH_FILES = ['auth.json']

/** What a generated scratch `config.toml` starts as, and why. */
const SCRATCH_CONFIG_HEADER = [
  '# Generated by the taurhaus E2E Codex compaction lane.',
  '# Only auth.json is copied out of the operator Codex home, so no integration',
  '# they configured (notify, MCP servers, sandbox overrides) runs during the',
  '# paid lane and taurhaus can install the notifier the lane reads turns from.',
].join('\n')

/**
 * Create `targetHome`, copy the credentials into it, and generate its config.
 *
 * Returns which files were copied, which were generated, and which were absent
 * — a missing `auth.json` is the signal that the lane cannot run, not an error
 * to throw. The copy holds a live subscription token, so it is written private
 * explicitly rather than inheriting whatever mode a reused path already had.
 */
export function createCodexScratchHome(sourceHome, targetHome) {
  mkdirSync(targetHome, { recursive: true })
  chmodSync(targetHome, 0o700)

  const copied = []
  const missing = []
  for (const name of CODEX_SCRATCH_FILES) {
    try {
      copyFileSync(join(sourceHome, name), join(targetHome, name))
      chmodSync(join(targetHome, name), 0o600)
      copied.push(name)
    } catch {
      missing.push(name)
    }
  }

  const configPath = join(targetHome, 'config.toml')
  writeFileSync(configPath, `${SCRATCH_CONFIG_HEADER}\n`)
  chmodSync(configPath, 0o600)

  return { home: targetHome, copied, generated: ['config.toml'], missing }
}

/**
 * Set Codex's auto-compaction threshold in a scratch `config.toml`.
 *
 * This is what bounds the automatic case: instead of paying for the ~250k
 * tokens a default context window needs, the run lowers the threshold and
 * reaches Codex's own auto-compaction after a couple of turns. TOML puts
 * top-level keys above the first table, so the key is inserted there.
 */
export function setAutoCompactTokenLimit(configPath, limit) {
  const key = 'model_auto_compact_token_limit'
  const assignment = `${key} = ${limit}`

  let lines = []
  try {
    lines = readFileSync(configPath, 'utf8').split('\n')
  } catch {
    lines = []
  }

  const existing = lines.findIndex((line) => line.trimStart().startsWith(`${key} `) || line.trimStart().startsWith(`${key}=`))
  if (existing >= 0) {
    lines[existing] = assignment
  } else {
    const firstTable = lines.findIndex((line) => line.trimStart().startsWith('['))
    const insertAt = firstTable < 0 ? lines.length : firstTable
    lines.splice(insertAt, 0, assignment)
  }

  const contents = lines.join('\n')
  writeFileSync(configPath, contents.endsWith('\n') ? contents : `${contents}\n`)
}

/**
 * Mark a directory trusted in a scratch `config.toml`.
 *
 * Codex stops at an interactive "Do you trust the contents of this directory?"
 * prompt for any unknown workspace — `--yolo` is an approval policy and does
 * not answer it — so a managed member launched in a fresh fixture project never
 * reaches its first turn. The operator's own projects carry this entry; the
 * scratch home needs it for the fixture path.
 */
export function trustProject(configPath, projectPath) {
  const table = `[projects.${JSON.stringify(projectPath)}]`

  let contents = ''
  try {
    contents = readFileSync(configPath, 'utf8')
  } catch {
    contents = ''
  }
  if (contents.includes(table)) return

  const prefix = contents.length === 0 || contents.endsWith('\n') ? '' : '\n'
  appendFileSync(configPath, `${prefix}\n${table}\ntrust_level = "trusted"\n`)
}
